# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72258de53f507c7aa46a8472ee7c04ef4055ce387baa520eaf8dd0845ba7ef7f59b766e8ffcd1d18e49098a36988c801431d567f26ba14c1cf8373644e5991b4

test:
  secret_key_base: d5f4338f25d30eb9331a1f60f73ef49942417e83a426b238313c3f3aa746204feba2c5680cb2179e5ab06d6d11724b1e2799d3b20672e791049e5293be957011

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
